wykop/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from wykop.accounts.views import BanUserView, RegistrationView

app_name = 'accounts'


urlpatterns = [
    path('login', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('rejestracja', RegistrationView.as_view(), name='register'),
    path('ban/<int:user_pk>', BanUserView.as_view(), name='ban'),
]

wykop/posts/urls.py
from django.urls import path

from wykop.posts.views import (CommentCreateView, PostCreate, PostDelete,
                               PostDetail, PostList, PostUpdate, TopPostsList)

app_name = 'posts'

urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('new', PostCreate.as_view(), name='create'),
    path('<int:pk>', PostDetail.as_view(), name='detail'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='update'),
    path('<int:pk>/delete', PostDelete.as_view(), name='delete'),
    path('top/', TopPostsList.as_view(), name='top-list'),
    path('comment/<int:post_pk>', CommentCreateView.as_view(), name='comment')
]

wykop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from wykop.posts.views import (HelloWorldView, PostCreate, PostDelete,
                               PostDetail, PostList, PostUpdate)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wykop.accounts.urls')),
    path('posts/', include('wykop.posts.urls')),
    # path('', hello_world),
    path('', HelloWorldView.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),
    path('api/', include('wykop.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

wykop/posts/models.py
from django.db import models
from django.db.models import deletion
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from embed_video.fields import EmbedVideoField

from wykop.accounts.models import User


class Post(models.Model):
    title = models.CharField(default='', max_length=150)
    text = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, deletion.PROTECT)
    image = models.ImageField(upload_to='post_images/', blank=True)
    video = EmbedVideoField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})


class Vote(models.Model):
    class Meta:
        unique_together = (
            ('user', 'post'),
        )
    PLUS = 1
    MINUS = -1
    VALUE_CHOICES = (
        (PLUS, '+'),
        (MINUS, '-'),
    )
    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(User, deletion.PROTECT, related_name='votes')
    post = models.ForeignKey(Post, deletion.PROTECT, related_name='votes')

    def __str__(self):
        return '({}) {} - {}'.format(
            self.get_value_display(),
            self.user,
            self.post,
        )


class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, deletion.PROTECT, related_name='comments')
    user = models.ForeignKey(User, deletion.PROTECT, related_name='comments')
    content = models.TextField(default='')

wykop/posts/forms.py
from django.forms.models import ModelForm

from wykop.posts.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

wykop/posts/views.py
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.aggregates import Sum
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView, View)
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.viewsets import ModelViewSet

from wykop.posts.forms import CommentForm
from wykop.posts.models import Comment
from wykop.posts.permissions import IsAuthorOrReadOnly
from wykop.posts.serializers import PostSerializer

from .models import Post

# def hello_world(request):
#     print(request)
#     # return HttpResponse('<b>Hello world!</b>')
#     return render(request, 'posts/index.html')

# class HelloWorldView(View):
#     def get(self, request, *args, **kwargs):
#           return render(request, 'posts/index.html')

class HelloWorldView(TemplateView):
    template_name = 'base.html'


class PostList(ListView):
    template_name = 'posts/list.html'
    # queryset = Post.objects.filter(published=True).order_by('-created')
    model = Post
    ordering = '-created'
    paginate_by = 3

    extra_context = {
        'title': 'Wpisy',
    }


class TopPostsList(PostList):
    queryset = Post.objects.annotate(score=Sum('votes__value')).order_by('-score')
    ordering = ''

    extra_context = {
        'title': 'Najlepsze wpisy',
    }


class PostDetail(DetailView):
    template_name = 'posts/detail.html'
    model = Post

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = self.object.title
        data['comment_form'] = CommentForm()
        return data


class PostCreate(LoginRequiredMixin, CreateView):
    template_name = 'posts/create.html'
    model = Post
    fields = ['title', 'text', 'image']

    extra_context = {
        'title': 'Dodawanie wpisu',
    }

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'posts/update.html'
    model = Post
    fields = ['title', 'text', 'image']

    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.author

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Edycja ' + self.object.title
        return data


class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'posts/delete.html'
    model = Post
    success_url = reverse_lazy('posts:list')

    def test_func(self):
        obj = self.get_object()
        return (
            (self.request.user == obj.author) and
            (timezone.now() - obj.created < timedelta(0, 15*60))
        )


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content']

    def dispatch(self, request, *args, **kwargs):
        if request.user.banned:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)   

    def get_post(self):
        post_pk = self.kwargs.get('post_pk')
        return Post.objects.get(pk=post_pk)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = self.get_post()
        return super().form_valid(form)

    def get_success_url(self):
        return self.get_post().get_absolute_url()


class PostViewSet(ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = (
        IsAuthenticatedOrReadOnly,
        IsAuthorOrReadOnly
    )

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

wykop/posts/templates/posts/comment.html
<div>
  <h6>{{ comment.user }}</h6>
  <small>{{ comment.created }}</small>
  <p>{{ comment.content }}</p>
</div>

wykop/posts/templates/posts/create.html
{% extends "base.html" %}

{% block content %}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Dodaj">
</form>
{% endblock %}

wykop/posts/templates/posts/delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Czy na pewno chcesz usunąć "{{ object }}"?</p>
    <input type="submit" value="Usuń">
</form>
{% endblock %}

wykop/posts/templates/posts/detail.html
{% extends "base.html" %}

{% load embed_video_tags %}

{% block content %}
    <small>{{ object.created|date }}, {{ object.created|time }} | <a href="{% url 'posts:update' pk=object.pk %}">Edytuj</a> | <a href="{% url 'posts:delete' pk=object.pk %}">Usuń</a> | autor: {{ object.author }}</small>

    {% if user.is_superuser %}
        <form method="post" action="{% url 'accounts:ban' object.author.pk %}">
            {% csrf_token %}

            {% if not object.author.banned %}
                <input type="hidden" name="set" value=1>
                <input type="submit" value="Zbanuj">
            {% else %}
                <input type="hidden" name="set" value=0>
                <input type="submit" value="Odbanuj">
            {% endif %}
        </form>
    {% endif %}

    <p>{{ object.text }}</p>
    {% if object.image %}
        <img src="{{ object.image.url }}">
    {% endif %}
    {% if object.video %}
        {% video object.video '800x600' %}
    {% endif %}

    <h4>Komentarze:</h4>

    <form method="post" action="{% url 'posts:comment' object.pk %}">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="Wyślij" {% if user.banned %} disabled {% endif %}>
    </form>

    {% for comment in object.comments.all %}
        {% include 'posts/comment.html' %}
    {% endfor %}

{% endblock %}

wykop/posts/templates/posts/list.html
{% extends "base.html" %}

{% load bootstrap_pagination %}

{% block header %}{{ block.super }} <a href="{% url 'posts:create' %}">+dodaj</a>{% endblock %}

{% block content %}
    <ul>
    {% for post in object_list %}
        <li>
            {{ post.created }} -
            <a href="{% url 'posts:detail' pk=post.pk %}">
                {{ post.title }}
            </a>
            {% if post.image %}
                <br>
                <img class="posts-list-img" src="{{ post.image.url }}">
            {% endif %}
        </li>
    {% empty %}
        <li>Brak wpisów.</li>
    {% endfor %}
    </ul>

    {% bootstrap_paginate page_obj show_first_last=True %}

{% endblock %}

wykop/posts/templates/posts/update.html
{% extends "base.html" %}

{% block content %}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Aktualizuj">
</form>
{% endblock %}