wykop/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from wykop.accounts.views import BanUserView, RegistrationView

app_name = 'accounts'


urlpatterns = [
    path('login', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('rejestracja', RegistrationView.as_view(), name='register'),
    path('ban/<int:user_pk>', BanUserView.as_view(), name='ban'),
]

wykop/posts/urls.py
from django.urls import path

from wykop.posts.views import (CommentCreateView, PostCreate, PostDelete,
                               PostDetail, PostList, PostUpdate, TopPostsList)

app_name = 'posts'

urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('new', PostCreate.as_view(), name='create'),
    path('<int:pk>', PostDetail.as_view(), name='detail'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='update'),
    path('<int:pk>/delete', PostDelete.as_view(), name='delete'),
    path('top/', TopPostsList.as_view(), name='top-list'),
    path('comment/<int:post_pk>', CommentCreateView.as_view(), name='comment')
]

wykop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from wykop.posts.views import (HelloWorldView, PostCreate, PostDelete,
                               PostDetail, PostList, PostUpdate)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wykop.accounts.urls')),
    path('posts/', include('wykop.posts.urls')),
    # path('', hello_world),
    path('', HelloWorldView.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token),
    path('api/', include('wykop.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

wykop/posts/models.py
from django.db import models
from django.db.models import deletion
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from embed_video.fields import EmbedVideoField

from wykop.accounts.models import User


class Post(models.Model):
    title = models.CharField(default='', max_length=150)
    text = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, deletion.PROTECT)
    image = models.ImageField(upload_to='post_images/', blank=True)
    video = EmbedVideoField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})


class Vote(models.Model):
    class Meta:
        unique_together = (
            ('user', 'post'),
        )
    PLUS = 1
    MINUS = -1
    VALUE_CHOICES = (
        (PLUS, '+'),
        (MINUS, '-'),
    )
    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(User, deletion.PROTECT, related_name='votes')
    post = models.ForeignKey(Post, deletion.PROTECT, related_name='votes')

    def __str__(self):
        return '({}) {} - {}'.format(
            self.get_value_display(),
            self.user,
            self.post,
        )


class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, deletion.PROTECT, related_name='comments')
    user = models.ForeignKey(User, deletion.PROTECT, related_name='comments')
    content = models.TextField(default='')

wykop/posts/forms.py
from django.forms.models import ModelForm

from wykop.posts.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

wykop/posts/views.py
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.aggregates import Sum
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView, View)
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.viewsets import ModelViewSet

from wykop.posts.forms import CommentForm
from wykop.posts.models import Comment
from wykop.posts.permissions import IsAuthorOrReadOnly
from wykop.posts.serializers import PostSerializer

from .models import Post

# def hello_world(request):
#     print(request)
#     # return HttpResponse('<b>Hello world!</b>')
#     return render(request, 'posts/index.html')

# class HelloWorldView(View):
#     def get(self, request, *args, **kwargs):
#           return render(request, 'posts/index.html')

class HelloWorldView(TemplateView):
    template_name = 'base.html'


class PostList(ListView):
    template_name = 'posts/list.html'
    # queryset = Post.objects.filter(published=True).order_by('-created')
    model = Post
    ordering = '-created'
    paginate_by = 3

    extra_context = {
        'title': 'Wpisy',
    }


class TopPostsList(PostList):
    queryset = Post.objects.annotate(score=Sum('votes__value')).order_by('-score')
    ordering = ''

    extra_context = {
        'title': 'Najlepsze wpisy',
    }


class PostDetail(DetailView):
    template_name = 'posts/detail.html'
    model = Post

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = self.object.title
        data['comment_form'] = CommentForm()
        return data


class PostCreate(LoginRequiredMixin, CreateView):
    template_name = 'posts/create.html'
    model = Post
    fields = ['title', 'text', 'image']

    extra_context = {
        'title': 'Dodawanie wpisu',
    }

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'posts/update.html'
    model = Post
    fields = ['title', 'text', 'image']

    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.author

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Edycja ' + self.object.title
        return data


class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'posts/delete.html'
    model = Post
    success_url = reverse_lazy('posts:list')

    def test_func(self):
        obj = self.get_object()
        return (
            (self.request.user == obj.author) and
            (timezone.now() - obj.created < timedelta(0, 15*60))
        )


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content']

    def dispatch(self, request, *args, **kwargs):
        if request.user.banned:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)   

    def get_post(self):
        post_pk = self.kwargs.get('post_pk')
        return Post.objects.get(pk=post_pk)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = self.get_post()
        return super().form_valid(form)

    def get_success_url(self):
        return self.get_post().get_absolute_url()


class PostViewSet(ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = (
        IsAuthenticatedOrReadOnly,
        IsAuthorOrReadOnly
    )

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

wykop/posts/templates/base.html
{% load static %}
<html>

<head>
  <title>{{ title }} - Mikroblog</title>
  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:list'%}">Posty</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:top-list'%}">Najlepsze</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Witaj, {{ request.user }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Wyloguj</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Zaloguj</a>
        </li>
        <li class="nav-item">
          <a class="nav-link btn btn-outline-success" href="{% url 'accounts:register' %}">Zarejestruj</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col">
        {% block header %}<h1>{{ title }}</h1>{% endblock %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>